### ISSUE TITLE
Configuration refactor

### ISSUE THREAD

**Issue by RichardFevrier** [eBay/event-notification-nodejs-sdk#1]
Hi everyone 👋 thank you for your work.

I'm posting this issue because I'm starting to implement this SDK and I saw the config file from your example.

```
{
    clientId: '---------',
    clientSecret: '---------',
    environment: 'PRODUCTION'
}
```

When we already have this for the `ebay-oauth-nodejs-client` 

```
{
    "SANDBOX": {
        "clientId": "---------",
        "clientSecret": "---------",
        "devid": "---------",
        "redirectUri": "---------",
        "baseUrl": "api.sandbox.ebay.com"
    },
    "PRODUCTION": {
        "clientId": "---------",
        "clientSecret": "---------",
        "devid": "---------",
        "redirectUri": "---------",
        "baseUrl": "api.ebay.com"
    }
}
```

And that for the `ebay-oauth-python-client`

```
{
	"name": "ebay-config",
	"api.sandbox.ebay.com": {
            "appid": "---------",
            "certid": "---------",
	    "devid": "---------",
	    "redirecturi": "---------"
	},
	"api.ebay.com": {
            "appid": "---------",
            "certid": "---------",
    	    "devid": "---------",
	    "redirecturi": "---------"
	}
}
```

It's kind of annoying to have multiple configuration files, which can cause errors..

Any chance that you will decide on a single template to rule them all?

Thank you for your time.

Best regards,

**Comment by LokeshRishi3** [comment]
Hello @RichardFevrier 

We appreciate your feedback and have published [v1.0.1](https://github.com/eBay/event-notification-nodejs-sdk/releases/tag/1.0.1) which updates the required config format, making it consistent with `ebay-oauth-nodejs-client`.

Let me know if you have any questions.
