### ISSUE TITLE
Help with config.js

### ISSUE THREAD

**Issue by sunrunner4kr-simon** [eBay/event-notification-nodejs-sdk#2]
Hi, Sorry I realise this is a stupid question, but unsure how to implement this.

Do I just need to change the client details as suggested in the nextjs-store\node_modules\event-notification-nodejs-sdk\examples\config.js that was installed?

Or do I need my own config.js

Thanks!

**Comment by LokeshRishi3** [comment]
Hello @sunrunner4kr-simon,

Thank you for reaching out.
I would recommend creating a config.js in your project and [passing it as a parameter to the EventNotificationSDK.process()](https://github.com/eBay/event-notification-nodejs-sdk/blob/main/examples/example.js#L39) method. 

Please let me know if you have any further questions.

**Comment by sunrunner4kr-simon** [comment]
Great, thanks for the help @LokeshRishi3 
Do you know how I can find out the names of the other topics to subscribe to?

I was looking to consume the EndOfAuction notification, but can't find any mention of 'topic' like the MARKETPLACE_ACCOUNT_DELETION topic that's in your example

https://developer.ebay.com/Devzone/guides/features-guide/default.html#notifications/Notif-EndOfAuction.html#Example

**Comment by LokeshRishi3** [comment]
Currently the SDK does not support that topic. 
You will be able to subscribe to it once eBay adds this topic in the new JSON format notifications.

**Comment by LokeshRishi3** [comment]
Closing as resolved.
