### ISSUE TITLE
Verification Token

### ISSUE THREAD

**Issue by iamsr** [eBay/event-notification-nodejs-sdk#4]
How do we get a verification token?

**Comment by LokeshRishi3** [comment]
Hello @iamsr, thank you for reaching out.

The token needs to be provided by the developer.
It should be between 32 and 80 characters long, and allowed characters include alphanumeric characters, underscore (_), and hyphen (-).

Please make sure to set up your endpoint to respond to challenge requests using the same verification token.
For more information, please refer to our documentation on [how to prepare your notification endpoint to receive eBay Marketplace Account Deletion/Closure Notifications](https://developer.ebay.com/marketplace-account-deletion#preparingURL).
