### ISSUE TITLE
Marketplace account deletion endpoint validation failed

### ISSUE THREAD

**Issue by yourcodesnotworking** [eBay/event-notification-nodejs-sdk#9]
**This one not working whatsoever!**
I has been search on the Google, trying find any single clue that may solve this funny issue, and still failed eventually.

Tried with fake challenge_code(_GET https://<callback_URL>?challenge_code=123),  url response json and hased string which hashed in the order that mention on this page(https://developer.ebay.com/marketplace-account-deletion), ie.ChallengCode, verificationToken,endpoint.

Funny part is that once you save page, it returns "Marketplace account deletion endpoint validation failed"

**Comment by LokeshRishi** [comment]
I'm closing this issue as it has been inactive for a while. Please reopen, if you still need assistance.
